[build]
  publish = "frontend/build"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
